---
title: "geodata"
output: html_document
date: "2023-06-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1) loading point data

```{r}
install.packages("readxl")
library(readxl)

sheet_names = excel_sheets("/Users/leamrowiec/Desktop/Datenanalyse SS23/era5_data_2006_2020_thailand_monmean.xlsx")

#laden von den einzelnen sheets
T.huss.mon = read_excel("/Users/leamrowiec/Desktop/Datenanalyse SS23/era5_data_2006_2020_thailand_monmean.xlsx", sheet="era5_huss_2006_2020_thailand_mo")
T.tp.mon = read_excel("/Users/leamrowiec/Desktop/Datenanalyse SS23/era5_data_2006_2020_thailand_monmean.xlsx", sheet="era5_tp_2006_2020_thailand_monm")
T.t2m.mon = read_excel("/Users/leamrowiec/Desktop/Datenanalyse SS23/era5_data_2006_2020_thailand_monmean.xlsx", sheet="era5_t2m_2006_2020_thailand_mon")

```

# a) Example 01: map with coordinate points of the centroids

```{r}
#assuming that longitude and latitude data in climate data are the centroids
centroids = T.huss.mon[,2:4] #including the names of the province to join the data later

# downloading the geo data (borders of districts)
library(sf)
geography <- st_read("/Users/leamrowiec/Desktop/Datenanalyse SS23/other data/gadm36_THA_shp")
```

```{r}
install.packages("dplyr")
library(dplyr)

# zeilen der dataframe centroids nach der reihenfolge der Distrikte in geography ordnen
centroids.ordered <- arrange(centroids, ADM1_EN) 
#aber: namen der distrikte sind nicht immer gleich -> hinzufügen einer Nummerierung der Dsitrikte, um gleiche spalte zu bekommen
centroids.ordered['numbers'] = c(1:77)
geography["numbers"] = c(1:77)


```

```{r}
install.packages("dplyr")
library(dplyr)
```

```{r}
# Zeilen beider dataframes (centroids und geography) nach alphabetischer reihenfolge der provinzen ordnen
centroids.sorted = arrange(centroids, ADM1_EN) #geography ist schon nach dem alphabet geordnet

#namen der distrikte sind nicht immer gleich -> hinzufügen einer Nummerierung der Dsitrikte, um gleiche spalte zu bekommen

centroids.sorted['numbers'] = c(1:77)
geography["numbers"] = c(1:77)


```

```{r}
# combining the two dataframes via the common column "numbers"
centroids.geography = merge(centroids.sorted, geography, by= "numbers")
# verview of data structure
class(centroids.geography)
head(centroids.geography)
summary(centroids.geography)
str(centroids.geography)

```

```{r}
install.packages("ggplot2")
library(ggplot2)
library(sf)
```

```{r}
install.packages("rgdal")
install.packages("data.table")

library(rgdal)
library(data.table)
```

```{r}
ggplot() +
  geom_sf(data = centroids.geography, aes(geometry=geometry),col = "black", fill = NA) +  # adds geometric layer of polygons stored in the data object
  geom_point(data = centroids.geography, aes(x = Longitude, y = Latitude)) # adds coordinate points
  
```

# b) Example 02: Map with data plotted over district area

```{r}
# plotting polygon data with ggplot2
# geography is dataframe with polygon data
class(geography)

# to plot the data we need a new dataframe combining geography data and relative humidity data

# 1. putting lines of dataframe T.huss.mon in alphabetical order of the province names
library(dplyr)
T.huss.mon.ordered = arrange(T.huss.mon, ADM1_EN) 

# 2. changing numers in column "Number"
#T.huss.mon.ordered = subset(T.huss.mon.ordered, select = -Number)
T.huss.mon.ordered['numbers'] = c(1:77)
# geography["numbers"] = c(1:77); numbers have already been added


```

```{r}

# using mean data of each province as a mean over all reported months
T.huss.mon.mean = apply(T.huss.mon.ordered[-c(1,2)], 1, mean)
T.huss.mon.mean.df = as.data.frame(T.huss.mon.mean)

# adding another column of numberst to merge the dataframes
T.huss.mon.mean.df['numbers'] = c(1:77)

# 3. merging the two dataframes of relative humidtiy and geography
huss.geography = merge(T.huss.mon.mean.df, geography, by= "numbers")


```

```{r}
ggplot() +
  geom_sf(data = huss.geography,aes(geometry = geometry, fill= T.huss.mon.mean), main= "mean temperature of each province") +
  coord_sf() +  
  theme_minimal() +
  labs(title = "mean relative humidity")
```

```{r}
# using max data of each province as a mean over all reported months
T.huss.mon.max = apply(T.huss.mon.ordered[-c(1,2)], 1, max)
T.huss.mon.max.df = as.data.frame(T.huss.mon.max)

# adding another column of numberst to merge the dataframes
T.huss.mon.max.df['numbers'] = c(1:77)

# merging the two dataframes of relative humidtiy and geography
huss.geography.max = merge(T.huss.mon.max.df, geography, by= "numbers")

# removing non-necessary colums of huss.geography.max
huss.geography.max.rmv = huss.geography.max[-c(3,4),]

ggplot() +
  geom_sf(data = huss.geography.max.rmv, aes(geometry = geometry), fill= T.huss.mon.max) +
  coord_sf() +  
  theme_minimal() +
  labs(title = "max relative humidity")

```

```{r}
install.packages("viridis")

# using max data of each province as a mean over all reported months
T.huss.mon.min = apply(T.huss.mon.ordered[-c(1,2)], 1, min)
T.huss.mon.min.df = as.data.frame(T.huss.mon.min)

# adding another column of numberst to merge the dataframes
T.huss.mon.min.df['numbers'] = c(1:77)

# 3. merging the two dataframes of relative humidtiy and geography
huss.geography = merge(T.huss.mon.min.df, geography, by= "numbers")




library(viridis)
library(ggplot2)

ggplot() +
  geom_sf(data = huss.geography,aes(geometry = geometry), fill= T.huss.mon.min) +
  coord_sf() +  
  theme_minimal() +
  labs(title = "min relative humidity") +
  scale_fill_viridis()
  
#cutting data to what we want to plot 


```

## c) geo facete plot of mean relative humidity (keine ahnung wie das gehen soll)

```{r}
install.packages("RColorBrewer")
install.packages("geofacet")
install.packages("magrittr")
install.packages("ggplot2")

library(RColorBrewer)
library(geofacet)
library(ggplot2)
library(dplyr)
library(magrittr)
 

cases_facet <- 
  data %>%  # this connects the data object
  group_by(year, month, day, adm2code) %>% # this groups the cases per month and year for each district
  # calculate state level incidence rate
  summarise(cases = sum(cases)) %>% 
  ggplot(aes(x = month, y = year, fill = cases)) + # for each facet plot it sets the time which is summarized per x and y axis
  geom_raster() + # creates a raster-based heatmap representing the data in color spectrum
  ylab("Year") + 
  xlab("Month") +
  scale_fill_gradientn(name = "# Dengue Cases", colours=brewer.pal(7, "PuRd"), trans = "log1p", breaks = c(0, 10, 100, 300, 1000), labels = c(0, 10, 100, 300, 1000) ) + 
  scale_y_discrete() +
  scale_x_discrete(labels = c("", "2", "", "4", "", "6", "", "8", "", "10", "", "12")) + # improved readability of the axis
  theme_bw() + 
  theme(plot.title = element_text(size = 25), axis.title = element_text(size = 20), legend.text = element_text(size = 20), legend.title = element_text(size = 20)) +
  # organise by district code in grid file
  facet_geo( ~ adm2code, grid = grid, label = "code") # arranges the facet plots position to each other

cases_facet


```
