---
title: "Paths_for_Clima_and_Dengue_Code"
author: "Manon Manddernach"
date: "2023-07-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
 
## Libraries to load
```{r}
library(sp)
library(sf)
library(terra)
library(dplyr)
library(raster)
library(ggplot2)
library(exactextractr)
library(readxl)
library(colorspace)
library(viridis)
library(viridisLite)
library(reshape2)
library(cluster)
```

## Loading Clima Data
```{r}
sheet_names = excel_sheets("../era5_data_2006_2020_thailand_monmean.xlsx")

T.huss.mon = read_excel("../era5_data_2006_2020_thailand_monmean.xlsx", sheet="era5_huss_2006_2020_thailand_mo")
T.tp.mon = read_excel("../era5_data_2006_2020_thailand_monmean.xlsx", sheet="era5_tp_2006_2020_thailand_monm")
T.t2m.mon = read_excel("../era5_data_2006_2020_thailand_monmean.xlsx", sheet="era5_t2m_2006_2020_thailand_mon")
```

## Defining T.Huss.mon 
```{r}
T.huss.mon.ordered = arrange(T.huss.mon, ADM1_EN) 
T.huss.mon.ordered['numbers'] = c(1:77)


```

## Loading the Geography Data
```{r}

geography <- st_read("./geo_data/gadm36_THA_shp")

```

 
 
