---
title: "How to upload excel sheets into R (dengue data set)"
output: html_document
date: "2023-05-30"
---

#Dengue data als dataframe einzeln einlesen in den Jahren 2006 - 2020:

```{r}
# Benötigte Bibliothek installieren
install.packages("readxl")
```

```{r}
# Benötigte Bibliothek laden
library(readxl)

# Relativer Pfad zur Excel-Datei
path2006 <- "./dengue data converted /2006_dengue_extracted.xlsx" 
path2007 <- "./dengue data converted /2007_dengue_extracted.xlsx"
path2008 <- "./dengue data converted /2008_dengue_extracted.xlsx" 
path2009 <- "./dengue data converted /2009_dengue_extracted.xlsx"
path2010 <- "./dengue data converted /2010_dengue_extracted.xlsx" 
path2011 <- "./dengue data converted /2011_dengue_extracted.xlsx"
path2012 <- "./dengue data converted /2012_dengue_extracted.xlsx" 
path2013 <- "./dengue data converted /2013_dengue_extracted.xlsx"
path2014 <- "./dengue data converted /2014_dengue_extracted.xlsx" 
path2015 <- "./dengue data converted /2015_dengue_extracted.xlsx"
path2016 <- "./dengue data converted /2016_dengue_extracted.xlsx" 
path2017 <- "./dengue data converted /2017_dengue_extracted.xlsx"
path2018 <- "./dengue data converted /2018_dengue_extracted.xlsx" 
path2019 <- "./dengue data converted /2019_dengue_extracted.xlsx"
path2020 <- "./dengue data converted /2010_dengue_extracted.xlsx" 


# Pfad zum Arbeitsverzeichnis setzen (wo die Excel-Datei liegt)
setwd(dirname(rstudioapi::getSourceEditorContext()$path))

# Excel-Datei einlesen und als Dataframe speichern
dengue2006 <- read_excel(path2006)
dengue2007 <- read_excel(path2007)

dengue2009 <- read_excel(path2009)
dengue2010 <- read_excel(path2010)
dengue2011 <- read_excel(path2011)
dengue2012 <- read_excel(path2012)
dengue2013 <- read_excel(path2013)
dengue2014 <- read_excel(path2014)
dengue2015 <- read_excel(path2015)
dengue2016 <- read_excel(path2016)
dengue2017 <- read_excel(path2017)
dengue2018 <- read_excel(path2018)
dengue2019 <- read_excel(path2019)
dengue2020 <- read_excel(path2020)

 
# Den eingelesenen Dataframe anzeigen
print(dengue2006)
print(dengue2007)
```
##Vereinfachtes einlesen mit schleife -> funktioniert noch nicht: 
- hab versucht es einfacher zu machen hat aber noch nicht geklappt 
- wenn sich da jemand drin auskennt gerne ausprobieren 
```{r}
#Liste der Dateinamen
file_names <- c("2006_dengue_extracted.xlsx", "2007_dengue_extracted.xlsx", "2009_dengue_extracted.xlsx", "2010_dengue_extracted.xlsx", "2011_dengue_extracted.xlsx", "2012_dengue_extracted.xlsx", "2013_dengue_extracted.xlsx", "2014_dengue_extracted.xlsx", "2015_dengue_extracted.xlsx", "2016_dengue_extracted.xlsx", "2017_dengue_extracted.xlsx", "2018_dengue_extracted.xlsx", "2019_dengue_extracted.xlsx","2020_dengue_extracted.xlsx")

# Relativer Pfad zum Ordner, in dem die Dateien liegen
folder_path <- "/Users/noemitigrato/Desktop/topic04_team01/dengue data converted"

# Leere Liste zum Speichern der eingelesenen Dataframes
data_list <- list()

# Liste zum Speichern der relativen Pfade
relative_paths <- list()

# Schleife zum Einlesen der Excel-Dateien
for (file_name in file_names) {
  
  # Konstruieren Sie den vollständigen relativen Pfad für jede Datei
  relative_paths <- paste0(folder_path,"/", file_name)
  
  # Excel-Datei einlesen und als Dataframe speichern
  dengue_data <- read_excel(relative_paths)
  
  # Dataframe zur Liste hinzufügen
  data_list[[file_name]] <- data
}
```

Dataframe für die Jahre 2006, 2007, 2009 , 2010 
```{r}
 
```



Angleichen der Daten von 2006 -2011 & 2017 - 2020 ohne Zonen zahlen an die der Jahre dazwischen
```{r}
rownames(dengue2006) = dengue2006$`Reporting areas`

#let`s remove the total Zone numbers and Regions 
i.remove = which(rownames(dengue2006) %in% c("Zone:1","Zone:4","Zone:2","Zone:5","Zone:6", "Zone:3","Zone:7", ))
```


